from unittest.mock import MagicMock
from views.viacep_view import ViacepView

def mock_viacep_repository() -> MagicMock: ...
def mock_viacep_service(mock_viacep_repository:MagicMock) -> MagicMock: ...
def create_view(mock_viacep_service:MagicMock) -> ViacepView: ...
